
export const TYPES = {
    IUsersRepository: Symbol.for('IUsersRepository'),
    IUsersService: Symbol.for('IUsersService'),
    UsersController: Symbol.for('UsersController'),
    IPostsRepository: Symbol.for('IPostsRepository'),
    IPostsService: Symbol.for('IPostsService'),
    PostsController: Symbol.for('PostsController'),
    IBloggersRepository: Symbol.for('IBloggersRepository'),
    IBloggersService: Symbol.for('IBloggersService'),
    BloggersController: Symbol.for('BloggersController'),
    ICommentsRepository: Symbol.for('ICommentsRepository'),
    ICommentsService: Symbol.for('ICommentsService'),
    CommentsController: Symbol.for('CommentsController'),
    JWTAuthMiddleware: Symbol.for('jwtAuthMiddleware'),
    JWTService: Symbol.for('JWTService'),
    AuthController: Symbol.for('AuthController'),
    BasicAuthMiddleware: Symbol.for('BasicAuthMiddleware'),
    PaginationMiddleware: Symbol.for('PaginationMiddleware'),
    BloggersCollection: Symbol.for('BloggersCollection'),
    CheckConnectionLimitsMiddleware: Symbol.for('CheckConnectionLimitsMiddleware'),
}